---
kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker:27.5
  commands:
  - apk add make git bash file
  - git config --global --add safe.directory /drone/src
  - make
  environment:
    ARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64
type: docker

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: docker:27.5
  commands:
  - apk add make git bash file
  - git config --global --add safe.directory /drone/src
  - make
  environment:
    ARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm
type: docker

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: docker:27.5
  commands:
  - apk add make git bash file
  - git config --global --add safe.directory /drone/src
  - make
  environment:
    ARCH: "${DRONE_STAGE_ARCH}"
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

...

